baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Joshua Ibrom | Systems-Focused Web Engineer'

[params]
hero_title = 'Building software'
hero_title_accent = 'closer to the metal'
bio = '''
I build minimalist web infrastructure and systems-level tooling,
currently focused on performance work with Zig and Rust.
'''
pseudoname = 'JOSH IBROM'

[menus]

[[menus.main]]
name = 'Projects'
url = '/projects'

[[menus.main]]
name = 'Writing'
url = '/posts'

[[menus.main]]
name = 'About'
url = '/about'

[[menus.hero]]
name = 'GitHub'
url = 'https://github.com/joshibrom'

[[menus.hero]]
name = 'LinkedIn'
url = 'https://linkedin.com/in/Joshua-Ibrom'

[[menus.footer]]
name = 'GitHub'
url = 'https://github.com/joshibrom'

[[menus.footer]]
name = 'LinkedIn'
url = 'https://linkedin.com/in/Joshua-Ibrom'
